development:
  dialect: postgres
  database: blog
  user: postgres
  password: mysecretpassword
  host: 127.0.0.1
  pool: 5

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/myapp_production"}}
  dialect: postgres
  pool: 1
  idle_pool: 1
